### ISSUE TITLE
Lightning vortex spell/scroll issue

### ISSUE THREAD

**Issue by Jennifercutixx** [Electroblob77/TF-Spell-Pack#13]
When useing lightning vortex spell/scroll in small spaces causes the spell to crash the game. Don't know if this issue has ever come up but it has happend to me more then once when testing. It only happens in small caves though. At the moment i just disabled the spell in the configs to stop further crashes when useing an unknown spell scroll.

**Comment by Electroblob77** [comment]
Not sure how you ended up on the tf spell pack issue tracker, pretty sure lightning vortex is from arcane essentials. Unless you mean carminite singularity? If you have a crash report I can still have a look at it though.

**Comment by Jennifercutixx** [comment]
might be an arcane essential spell, plus doesnt give crash report since been ages. Soz for late post was rll busy. but ill see and it seems that it would be an arcane essential spell since u dont know it.

**Comment by Jennifercutixx** [comment]
Sorry, for the confusion this issue is for arcane essentials, since vortex is within that mod. i shall close this issue since nothing to do with your mod.
