### ISSUE TITLE
Bug after blobs update

### ISSUE THREAD

**Issue by bigenergy** [Electroblob77/TF-Spell-Pack#14]
https://www.curseforge.com/minecraft/mc-mods/electroblobs-wizardry-twilight-forest-spell-pack?comment=62

**Comment by Shibva** [comment]
Yes, the version for the mod is not allowing for the latest version of the mod with its new update

says it needs to be below the specified version

**Comment by MattLikesGaming** [comment]
New update and still shows the update required even though I have the latest version 4.3.1 says it requires 4.3.
![Capture](https://user-images.githubusercontent.com/39849197/98025835-11d40a00-1dbf-11eb-9118-d7888564118b.PNG)
