### ISSUE TITLE
Electroblob's Wizardry: Twilight Forest Spell Pack mod incompatible with Electroblob's Wizardry newly updated main mod.

### ISSUE THREAD

**Issue by MattLikesGaming** [Electroblob77/TF-Spell-Pack#15]
The new update and still shows the update required for Electroblob's Wizardry mod even though Electroblob's Wizardry: Twilight Forest Spell Pack I have the latest version 4.3.1 but says it requires version 4.3 for Electroblob's Wizardry main mod.
![Capture](https://user-images.githubusercontent.com/39849197/98026278-ba826980-1dbf-11eb-862a-d942ef57098f.PNG)

**Comment by PercyJames** [comment]
it also means i can't use ancient spellcraft!

**Comment by TUsama** [comment]
This is on purpose. TFspell will be updated when the EBwizardry becomes stable.

**Comment by Shibva** [comment]
ooooooooh, well that explains some things

thanks for the info

**Comment by MattLikesGaming** [comment]
Thanks for the info.
