### ISSUE TITLE
Spell chariot_of_ice causes crash client

### ISSUE THREAD

**Issue by bigenergy** [Electroblob77/TF-Spell-Pack#3]
Spell chariot_of_ice - crash client on use wand

https://pastebin.com/cKSZ9qCC

**Comment by omerbadawy11** [comment]
yeah same here

**Comment by Electroblob77** [comment]
Can confirm this does not happen for me on a clean installation with wizardry, twilight forest and TF spell pack. Please can someone experiencing this issue post a full log? Something is causing that particular spell properties file not to load properly, the startup log might have some info as to why.

**Comment by TheMightyMcGrew** [comment]
Also providing confirmation as well as info, this only happens for me on a server, in singleplayer with all the same mods and such it works fine, but as soon as its tried on a server it crashs/disconnects

**Comment by Electroblob77** [comment]
This is almost certainly issue #7 if it happens only on a server. Why on earth the crash report in OP happened I don't know, but it's not the same one. I am closing this issue, but #7 should be fixed in the next patch.
