### ISSUE TITLE
Server crash appears related to TF Spell Pack

### ISSUE THREAD

**Issue by ghost** [Electroblob77/TF-Spell-Pack#4]
I have no more details, unfortunately, because I wasn't the one who triggered the crash and can't reach the person who was. [Here's the crash log](https://pastebin.com/PdBksPBM), and [here is the crash in the debug log](https://pastebin.com/SfHZKh7Y).

**Comment by Luke616** [comment]
Obtaining a similar crash, looks like its related to twilight mages who try to use the "Call of the Horn" spell. Here's my log too, if it helps 
[crash-2020-03-30_00.31.13-server.txt](https://github.com/Electroblob77/TF-Spell-Pack/files/4400299/crash-2020-03-30_00.31.13-server.txt)

**Comment by Electroblob77** [comment]
Druid mages probably shouldn't be trying to cast it at all... guess I'll just disable that. Thanks for the reports.
